package com.arun.mymessages;
import android.app.*;import android.os.*;import android.content.*;import android.database.*;import android.net.*;import android.provider.Telephony;import android.widget.*;import java.io.*;import org.json.*;
public class BackupActivity extends Activity{
 public void onCreate(Bundle b){super.onCreate(b);LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setPadding(20,20,20,20);x.setBackgroundColor(0xfffaf8f4);
 TextView h=new TextView(this);h.setText("Backup & Restore");h.setTextSize(24);h.setTextColor(0xffffffff);h.setBackgroundColor(0xff312c51);h.setPadding(18,18,18,18);x.addView(h);
 Button ex=new Button(this);ex.setText("Export SMS backup (.json)");x.addView(ex);ex.setOnClickListener(v->exportFile());
 Button im=new Button(this);im.setText("Import backup");x.addView(im);im.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,20);});
 TextView n=new TextView(this);n.setText("Backup contains message text, address, date and type. Android controls whether another app can write SMS to the system inbox.");n.setTextSize(14);n.setPadding(8,20,8,8);x.addView(n);setContentView(x);}
 void exportFile(){try{JSONArray a=new JSONArray();Cursor c=getContentResolver().query(Telephony.Sms.CONTENT_URI,new String[]{"address","body","date","type","read"} ,null,null,"date ASC");if(c!=null){while(c.moveToNext()){JSONObject o=new JSONObject();o.put("address",c.getString(0));o.put("body",c.getString(1));o.put("date",c.getLong(2));o.put("type",c.getInt(3));o.put("read",c.getInt(4));a.put(o);}c.close();}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"my_messages_backup.json");getPreferences(0).edit().putString("pending",a.toString()).apply();startActivityForResult(i,21);}catch(Exception e){err(e);}}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==21&&c==RESULT_OK&&d!=null)try{OutputStream o=getContentResolver().openOutputStream(d.getData());o.write(getPreferences(0).getString("pending","[]").getBytes("UTF-8"));o.close();Toast.makeText(this,"Backup saved",Toast.LENGTH_LONG).show();}catch(Exception e){err(e);}else if(r==20&&c==RESULT_OK&&d!=null)importFile(d.getData());}
 void importFile(android.net.Uri uri){try{java.io.InputStream in=getContentResolver().openInputStream(uri);java.io.ByteArrayOutputStream b=new java.io.ByteArrayOutputStream();byte[] q=new byte[8192];int n;while((n=in.read(q))>0)b.write(q,0,n);in.close();org.json.JSONArray a=new org.json.JSONArray(new String(b.toByteArray(),"UTF-8"));new AlertDialog.Builder(this).setTitle("Restore backup").setMessage("Restore "+a.length()+" messages into the device SMS database?").setNegativeButton("Cancel",null).setPositiveButton("Restore",(d,w)->{int ok=0;for(int k=0;k<a.length();k++)try{org.json.JSONObject o=a.getJSONObject(k);android.content.ContentValues v=new android.content.ContentValues();v.put("address",o.optString("address"));v.put("body",o.optString("body"));v.put("date",o.optLong("date"));v.put("type",o.optInt("type",1));v.put("read",o.optInt("read",1));getContentResolver().insert(Telephony.Sms.CONTENT_URI,v);ok++;}catch(Exception ignored){}Toast.makeText(this,"Restored "+ok+" messages",Toast.LENGTH_LONG).show();}).show();}catch(Exception e){err(e);}}
 void err(Exception e){new AlertDialog.Builder(this).setTitle("Backup error").setMessage(e.toString()).setPositiveButton("OK",null).show();}
}