package com.arun.mymessages;
import android.app.*;import android.os.*;import android.content.*;import android.net.Uri;import android.database.*;import android.provider.Telephony;import android.widget.*;import java.io.*;import org.json.*;import java.util.*;

public class BackupActivity extends Activity{
 LinearLayout root;TextView info;
 public void onCreate(Bundle b){super.onCreate(b);build();}
 void build(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(16,16,16,16);root.setBackgroundColor(getSharedPreferences("settings",0).getBoolean("dark",false)?0xff18161f:0xfffaf8f4);
 TextView h=new TextView(this);h.setText("Backup & Restore");h.setTextSize(24);h.setTextColor(0xffffffff);h.setBackgroundColor(0xff312c51);h.setPadding(18,18,18,18);root.addView(h);
 Button ex=new Button(this);ex.setText("Backup now • Export JSON");root.addView(ex);ex.setOnClickListener(v->exportFile());
 Button im=new Button(this);im.setText("Restore from JSON");root.addView(im);im.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,20);});
 info=new TextView(this);info.setTextColor(getSharedPreferences("settings",0).getBoolean("dark",false)?0xfff5f2fa:0xff312c51);info.setPadding(8,20,8,8);root.addView(info);refreshInfo();
 TextView note=new TextView(this);note.setText("Automatic backups are stored locally inside the app and never overwrite your exported JSON files.");note.setPadding(8,8,8,8);root.addView(note);setContentView(root);}
 void refreshInfo(){File dir=new File(getFilesDir(),"backups");File[] fs=dir.exists()?dir.listFiles():null;StringBuilder s=new StringBuilder("Automatic backup history\nFolder: "+BackupUtil.backupFolder(this)+"\n");if(fs==null||fs.length==0)s.append("No automatic backups yet.");else{Arrays.sort(fs,(a,b)->Long.compare(b.lastModified(),a.lastModified()));for(File f:fs)s.append("• ").append(f.getName()).append(" • ").append(new java.text.SimpleDateFormat("dd MMM yyyy, hh:mm a",Locale.US).format(new Date(f.lastModified()))).append("\n");}info.setText(s.toString());}
 void exportFile(){try{JSONArray a=BackupUtil.readSms(this);Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"my_messages_backup_"+new java.text.SimpleDateFormat("yyyy-MM-dd_HHmm",Locale.US).format(new Date())+".json");getPreferences(0).edit().putString("pending",a.toString()).apply();startActivityForResult(i,21);}catch(Exception e){err(e);}}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==21&&c==RESULT_OK&&d!=null)try{OutputStream o=getContentResolver().openOutputStream(d.getData());o.write(getPreferences(0).getString("pending","[]").getBytes("UTF-8"));o.close();Toast.makeText(this,"Backup saved",Toast.LENGTH_LONG).show();}catch(Exception e){err(e);}else if(r==20&&c==RESULT_OK&&d!=null)importFile(d.getData());}
 void importFile(Uri uri){try{InputStream in=getContentResolver().openInputStream(uri);ByteArrayOutputStream b=new ByteArrayOutputStream();byte[] q=new byte[8192];int n;while((n=in.read(q))>0)b.write(q,0,n);in.close();JSONArray a=new JSONArray(new String(b.toByteArray(),"UTF-8"));new AlertDialog.Builder(this).setTitle("Restore backup").setMessage("Restore "+a.length()+" messages into the device SMS database?").setNegativeButton("Cancel",null).setPositiveButton("Restore",(d,w)->{int ok=0;for(int k=0;k<a.length();k++)try{JSONObject o=a.getJSONObject(k);ContentValues v=new ContentValues();v.put("address",o.optString("address"));v.put("body",o.optString("body"));v.put("date",o.optLong("date"));v.put("type",o.optInt("type",1));v.put("read",o.optInt("read",1));getContentResolver().insert(Telephony.Sms.CONTENT_URI,v);ok++;}catch(Exception ignored){}Toast.makeText(this,"Restored "+ok+" messages",Toast.LENGTH_LONG).show();}).show();}catch(Exception e){err(e);}}
 void err(Exception e){new AlertDialog.Builder(this).setTitle("Backup error").setMessage(e.toString()).setPositiveButton("OK",null).show();}
}