package com.arun.mymessages;
import android.app.*;import android.os.*;import android.content.*;import android.telephony.SmsManager;import android.graphics.Color;import android.view.*;import android.widget.*;import android.database.Cursor;import android.provider.Telephony;import java.text.*;import java.util.*;
public class ConversationActivity extends Activity{
 LinearLayout msgs;String thread,number,name;int primary=Color.rgb(49,44,81),purple=Color.rgb(122,63,240);
 TextView t(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(16,10,16,10);return v;}
 public void onCreate(Bundle b){super.onCreate(b);thread=getIntent().getStringExtra("thread");number=getIntent().getStringExtra("number");name=getIntent().getStringExtra("name");ui();load();}
 void ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);TextView h=t("‹  "+name+"\n"+number,18,Color.WHITE);h.setBackgroundColor(primary);h.setOnClickListener(v->finish());r.addView(h);ScrollView s=new ScrollView(this);msgs=new LinearLayout(this);msgs.setOrientation(LinearLayout.VERTICAL);s.addView(msgs);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));LinearLayout bar=new LinearLayout(this);EditText in=new EditText(this);in.setHint("Message");Button send=new Button(this);send.setText("SEND");send.setTextColor(Color.WHITE);send.setBackgroundColor(purple);bar.addView(in,new LinearLayout.LayoutParams(0,62,1));bar.addView(send,new LinearLayout.LayoutParams(95,62));send.setOnClickListener(v->{String x=in.getText().toString().trim();if(!x.isEmpty()){send(x);in.setText("");}});r.addView(bar);setContentView(r);}
 void load(){msgs.removeAllViews();try{String sel=thread==null?"address=?":"thread_id=?";String arg=thread==null?number:thread;Cursor c=getContentResolver().query(Telephony.Sms.CONTENT_URI,new String[]{"body","date","type"},sel,new String[]{arg},"date ASC");if(c!=null){while(c.moveToNext()){boolean sent=c.getInt(2)==Telephony.Sms.MESSAGE_TYPE_SENT;TextView v=t(c.getString(0)+"\n"+new SimpleDateFormat("dd MMM hh:mm a").format(new Date(c.getLong(1))),15,sent?primary:Color.DKGRAY);v.setGravity(sent?Gravity.RIGHT:Gravity.LEFT);v.setBackgroundColor(sent?Color.rgb(240,195,142):Color.WHITE);msgs.addView(v,new LinearLayout.LayoutParams(-1,-2));}c.close();}}catch(Exception e){}}
 void send(String x){try{SmsManager sm=SmsManager.getDefault();ArrayList<String> p=sm.divideMessage(x);if(p.size()==1)sm.sendTextMessage(number,null,x,null,null);else sm.sendMultipartTextMessage(number,null,p,null,null);load();}catch(Exception e){new AlertDialog.Builder(this).setTitle("Send failed").setMessage(e.toString()).setPositiveButton("OK",null).show();}}
}