package com.arun.mymessages;
import android.app.*;import android.os.*;import android.content.*;import android.telephony.*;import android.graphics.Color;import android.view.*;import android.widget.*;import android.database.Cursor;import android.provider.Telephony;import java.text.*;import java.util.*;
public class ConversationActivity extends Activity{
 LinearLayout msgs;String thread,number,name;int primary=Color.rgb(49,44,81),purple=Color.rgb(122,63,240);int subId=SubscriptionManager.INVALID_SUBSCRIPTION_ID;
 TextView t(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(16,10,16,10);return v;}
 public void onCreate(Bundle b){super.onCreate(b);thread=getIntent().getStringExtra("thread");number=getIntent().getStringExtra("number");name=getIntent().getStringExtra("name");ui();load();}
 void ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);TextView h=t("‹  "+name+"\n"+number,18,Color.WHITE);h.setBackgroundColor(primary);h.setOnClickListener(v->finish());r.addView(h);
 ScrollView s=new ScrollView(this);msgs=new LinearLayout(this);msgs.setOrientation(LinearLayout.VERTICAL);s.addView(msgs);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));
 LinearLayout bar=new LinearLayout(this);Spinner sim=new Spinner(this);ArrayList<String> sims=new ArrayList<>();sims.add("Default SIM");if(Build.VERSION.SDK_INT>=22)try{for(SubscriptionInfo x:SubscriptionManager.from(this).getActiveSubscriptionInfoList())sims.add("SIM "+x.getSimSlotIndex()+": "+x.getDisplayName());}catch(Exception e){}ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,sims);sim.setAdapter(a);bar.addView(sim,new LinearLayout.LayoutParams(120,62));
 EditText in=new EditText(this);in.setHint("Message");Button attach=new Button(this);attach.setText("📎");bar.addView(attach,new LinearLayout.LayoutParams(55,62));Button send=new Button(this);send.setText("SEND");send.setTextColor(Color.WHITE);send.setBackgroundColor(purple);bar.addView(in,new LinearLayout.LayoutParams(0,62,1));bar.addView(send,new LinearLayout.LayoutParams(85,62));attach.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_GET_CONTENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(Intent.createChooser(i,"Attach file"),44);});send.setOnClickListener(v->{String x=in.getText().toString().trim();if(!x.isEmpty()){send(x,sim.getSelectedItemPosition());in.setText("");}});r.addView(bar);setContentView(r);}
 void load(){msgs.removeAllViews();try{String sel=thread==null?"address=?":"thread_id=?";String arg=thread==null?number:thread;Cursor c=getContentResolver().query(Telephony.Sms.CONTENT_URI,new String[]{"body","date","type","status"},sel,new String[]{arg},"date ASC");if(c!=null){while(c.moveToNext()){final String body=c.getString(0);final long date=c.getLong(1);boolean sent=c.getInt(2)==Telephony.Sms.MESSAGE_TYPE_SENT;String st=c.isNull(3)?"":(" • status "+c.getInt(3));TextView v=t(body+"\n"+new SimpleDateFormat("dd MMM hh:mm a").format(new Date(date))+(sent?st:""),15,sent?primary:Color.DKGRAY);v.setGravity(sent?Gravity.RIGHT:Gravity.LEFT);v.setBackgroundColor(sent?Color.rgb(240,195,142):Color.WHITE);v.setOnLongClickListener(q->{new AlertDialog.Builder(this).setItems(new String[]{"Copy","Delete message","Forward"},(d,w)->{if(w==0){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(android.content.ClipData.newPlainText("message",body));}else if(w==1)deleteMessage(date,body);else {Intent i=new Intent(Intent.ACTION_SENDTO,android.net.Uri.parse("smsto:"));i.putExtra("sms_body",body);startActivity(i);}}).show();return true;});msgs.addView(v,new LinearLayout.LayoutParams(-1,-2));}c.close();}}catch(Exception e){}}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==44&&c==RESULT_OK&&d!=null&&d.getData()!=null){try{Intent i=new Intent(Intent.ACTION_SEND);i.setType(getContentResolver().getType(d.getData())==null?"application/octet-stream":getContentResolver().getType(d.getData()));i.putExtra(Intent.EXTRA_STREAM,d.getData());i.putExtra("address",number);startActivity(Intent.createChooser(i,"Send attachment"));}catch(Exception e){}}}\n void deleteMessage(long date,String body){try{getContentResolver().delete(Telephony.Sms.CONTENT_URI,"date=? AND body=?",new String[]{String.valueOf(date),body});load();}catch(Exception e){}}
 void send(String x,int which){try{SmsManager sm;if(Build.VERSION.SDK_INT>=22&&which>0){List<SubscriptionInfo> l=SubscriptionManager.from(this).getActiveSubscriptionInfoList();if(l!=null&&which-1<l.size())sm=SmsManager.getSmsManagerForSubscriptionId(l.get(which-1).getSubscriptionId());else sm=SmsManager.getDefaultSmsSubscriptionId()==SubscriptionManager.INVALID_SUBSCRIPTION_ID?SmsManager.getDefault():SmsManager.getSmsManagerForSubscriptionId(SmsManager.getDefaultSmsSubscriptionId());}else sm=SmsManager.getDefault();ArrayList<String> p=sm.divideMessage(x);if(p.size()==1)sm.sendTextMessage(number,null,x,null,null);else sm.sendMultipartTextMessage(number,null,p,null,null);load();}catch(Exception e){new AlertDialog.Builder(this).setTitle("Send failed").setMessage(e.toString()).setPositiveButton("OK",null).show();}}
}