package com.arun.mymessages;
import android.app.*;import android.os.*;import android.content.*;import android.text.InputType;import android.view.*;import android.widget.*;import androidx.biometric.BiometricPrompt;import androidx.core.content.ContextCompat;import java.util.concurrent.Executor;

public class LockActivity extends Activity{
 public void onCreate(Bundle b){super.onCreate(b);SharedPreferences p=getSharedPreferences("settings",0);if(p.getBoolean("biometric",false)){showBiometric();}else showPin();}
 void showBiometric(){Executor ex=ContextCompat.getMainExecutor(this);BiometricPrompt prompt=new BiometricPrompt(this,ex,new BiometricPrompt.AuthenticationCallback(){public void onAuthenticationSucceeded(BiometricPrompt.AuthenticationResult r){finish();}public void onAuthenticationError(int code,CharSequence msg){showPin();}public void onAuthenticationFailed(){}});BiometricPrompt.PromptInfo info=new BiometricPrompt.PromptInfo.Builder().setTitle("My Messages").setSubtitle("Unlock your private messages").setDescription("Use fingerprint or device biometric").setNegativeButtonText("Use PIN").build();prompt.authenticate(info);}
 void showPin(){final EditText e=new EditText(this);e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_VARIATION_PASSWORD);e.setHint("Enter PIN");e.setTextSize(22);e.setPadding(30,30,30,30);
 final AlertDialog a=new AlertDialog.Builder(this).setTitle("My Messages locked").setMessage("Enter your PIN to continue").setView(e).setCancelable(false).setPositiveButton("Unlock",null).setNegativeButton("Exit",(d,w)->finishAffinity()).create();
 a.setOnShowListener(d->{a.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String p=getSharedPreferences("settings",0).getString("pin","");if(e.getText().toString().equals(p)){a.dismiss();finish();}else e.setError("Wrong PIN");});});a.show();}
}