package com.arun.mymessages;
import android.Manifest;import android.app.*;import android.app.role.RoleManager;import android.content.*;import android.content.pm.PackageManager;import android.database.Cursor;import android.net.Uri;import android.os.*;import android.provider.ContactsContract;import android.provider.Telephony;import android.graphics.Color;import android.view.*;import android.widget.*;import android.text.*;import java.util.*;
public class MainActivity extends Activity{
 LinearLayout list; EditText search; ArrayList<ThreadRow> data=new ArrayList<>(); int primary=Color.rgb(49,44,81),purple=Color.rgb(122,63,240),bg=Color.rgb(250,248,244);
 TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(16,10,12,10);return v;}
 Button bt(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setBackgroundColor(primary);return b;}
 @Override public void onCreate(Bundle b){super.onCreate(b);permissions();ui();load();}
 void permissions(){if(Build.VERSION.SDK_INT>=23)requestPermissions(new String[]{Manifest.permission.READ_SMS,Manifest.permission.RECEIVE_SMS,Manifest.permission.SEND_SMS,Manifest.permission.READ_CONTACTS,Manifest.permission.POST_NOTIFICATIONS},5);if(Build.VERSION.SDK_INT>=29){RoleManager r=getSystemService(RoleManager.class);if(r!=null&&r.isRoleAvailable(RoleManager.ROLE_SMS)&&!r.isRoleHeld(RoleManager.ROLE_SMS))startActivityForResult(r.createRequestRoleIntent(RoleManager.ROLE_SMS),9);}}
 void ui(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);
 TextView h=tv("My Messages",23,Color.WHITE);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(22,0,0,0);h.setBackgroundColor(primary);root.addView(h,new LinearLayout.LayoutParams(-1,68));
 LinearLayout s=new LinearLayout(this);search=new EditText(this);search.setHint("Search name, number or message");search.setSingleLine();s.addView(search,new LinearLayout.LayoutParams(0,58,1));Button add=bt("＋");s.addView(add,new LinearLayout.LayoutParams(62,58));root.addView(s);
 ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
 LinearLayout nav=new LinearLayout(this);for(String n:new String[]{"Inbox","Pinned","Archived","Blocked","Backup"}){Button x=bt(n);nav.addView(x,new LinearLayout.LayoutParams(0,60,1));x.setOnClickListener(v->{if(n.equals("Backup"))backup();else show(n);});}root.addView(nav);setContentView(root);
 search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){render(s.toString(),"Inbox");}public void afterTextChanged(Editable e){}});add.setOnClickListener(v->newChat());}
 void load(){data.clear();try{Cursor c=getContentResolver().query(Telephony.Sms.CONTENT_URI,new String[]{"thread_id","address","body","date","read"},null,null,"date DESC");HashSet<String> seen=new HashSet<>();if(c!=null){while(c.moveToNext()){String id=c.getString(0);if(seen.contains(id))continue;seen.add(id);ThreadRow r=new ThreadRow();r.thread=id;r.number=c.getString(1);r.body=c.getString(2);r.name=name(r.number);r.read=c.getInt(4);r.pin=pref("p",id);r.arc=pref("a",id);r.block=pref("b",id);data.add(r);}c.close();}}catch(Exception e){}render("","Inbox");}
 String name(String n){try{Cursor c=getContentResolver().query(Uri.withAppendedPath(ContactsContract.PhoneLookup.CONTENT_FILTER_URI,Uri.encode(n)),new String[]{ContactsContract.PhoneLookup.DISPLAY_NAME},null,null,null);if(c!=null&&c.moveToFirst()){String x=c.getString(0);c.close();return x;}}catch(Exception e){}return n==null?"Unknown":n;}
 void render(String q,String mode){list.removeAllViews();for(ThreadRow r:data){if(mode.equals("Inbox")&&r.arc)continue;if(mode.equals("Pinned")&&!r.pin)continue;if(mode.equals("Archived")&&!r.arc)continue;if(mode.equals("Blocked")&&!r.block)continue;String z=(r.name+" "+r.number+" "+r.body).toLowerCase();if(!z.contains(q.toLowerCase()))continue;row(r);}if(list.getChildCount()==0)list.addView(tv("No conversations",18,Color.DKGRAY));}
 void row(ThreadRow r){LinearLayout x=new LinearLayout(this);x.setGravity(Gravity.CENTER_VERTICAL);TextView av=tv((r.name+"").substring(0,1).toUpperCase(),22,Color.WHITE);av.setGravity(Gravity.CENTER);av.setBackgroundColor(purple);x.addView(av,new LinearLayout.LayoutParams(54,54));LinearLayout m=new LinearLayout(this);m.setOrientation(LinearLayout.VERTICAL);m.addView(tv(r.name,17,primary));m.addView(tv(r.body==null?"":r.body,14,Color.DKGRAY));x.addView(m,new LinearLayout.LayoutParams(0,76,1));x.addView(tv(r.pin?"★":"",18,Color.rgb(220,150,30)));x.setOnClickListener(v->open(r));x.setOnLongClickListener(v->{menu(r);return true;});list.addView(x);}
 void open(ThreadRow r){Intent i=new Intent(this,ConversationActivity.class);i.putExtra("thread",r.thread);i.putExtra("number",r.number);i.putExtra("name",r.name);startActivity(i);}
 void menu(ThreadRow r){String[] a={r.pin?"Unpin":"Pin",r.arc?"Unarchive":"Archive",r.block?"Unblock":"Block","Mark read","Delete"};new AlertDialog.Builder(this).setTitle(r.name).setItems(a,(d,w)->{if(w==0)save("p",r.thread,!r.pin);else if(w==1)save("a",r.thread,!r.arc);else if(w==2)save("b",r.thread,!r.block);else if(w==3){try{ContentValues v=new ContentValues();v.put("read",1);getContentResolver().update(Telephony.Sms.CONTENT_URI,v,"thread_id=?",new String[]{r.thread});}catch(Exception e){}}else try{getContentResolver().delete(Telephony.Sms.CONTENT_URI,"thread_id=?",new String[]{r.thread});}catch(Exception e){}load();}).show();}
 void show(String mode){render(search.getText().toString(),mode);}
 void newChat(){EditText e=new EditText(this);e.setHint("Phone number");new AlertDialog.Builder(this).setTitle("New conversation").setView(e).setPositiveButton("Open",(d,w)->{Intent i=new Intent(this,ConversationActivity.class);i.putExtra("number",e.getText().toString());i.putExtra("name",e.getText().toString());startActivity(i);}).setNegativeButton("Cancel",null).show();}
 void backup(){StringBuilder s=new StringBuilder("My Messages backup\n");for(ThreadRow r:data)s.append(r.number).append("|").append(r.body).append("\n");getPreferences(0).edit().putString("backup",s.toString()).apply();Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("text/plain");i.putExtra(Intent.EXTRA_TITLE,"my_messages_backup.txt");startActivityForResult(i,50);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==50&&c==RESULT_OK&&d!=null)try{String s=getPreferences(0).getString("backup","");java.io.OutputStream o=getContentResolver().openOutputStream(d.getData());o.write(s.getBytes());o.close();}catch(Exception e){}}
 boolean pref(String p,String k){return getPreferences(0).getBoolean(p+k,false);}void save(String p,String k,boolean v){getPreferences(0).edit().putBoolean(p+k,v).apply();}
 static class ThreadRow{String thread,number,name,body;int read;boolean pin,arc,block;}
}