package com.arun.mymessages;

import android.Manifest;import android.app.*;import android.app.role.RoleManager;import android.content.*;import android.database.Cursor;import android.net.Uri;import android.os.*;import android.provider.ContactsContract;import android.provider.Telephony;import android.graphics.Color;import android.view.*;import android.widget.*;import android.text.*;import java.util.*;

public class MainActivity extends Activity{
 LinearLayout list;EditText search;ArrayList<ThreadRow> data=new ArrayList<>();HashSet<String> selected=new HashSet<>();
 int primary=Color.rgb(49,44,81),purple=Color.rgb(122,63,240),lightBg=Color.rgb(250,248,244),darkBg=Color.rgb(24,22,31);String mode="Inbox";boolean dark;ThreadRow pendingPrivate;
 int fg(){return dark?Color.rgb(245,242,250):Color.rgb(36,33,51);}int sub(){return dark?Color.rgb(195,190,205):Color.DKGRAY;}
 TextView tv(String s,int z,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);v.setPadding(16,10,12,10);return v;}
 Button bt(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setBackgroundColor(primary);return b;}
 public void onCreate(Bundle b){super.onCreate(b);dark=getSharedPreferences("settings",0).getBoolean("dark",false);SharedPreferences p=getSharedPreferences("settings",0);if(p.getBoolean("lock",false)&&(p.getString("pin","").length()>0||p.getBoolean("biometric",false)))startActivity(new Intent(this,LockActivity.class));ui();requestSmsRoleThenPermissions();load();autoBackupIfNeeded();}
 protected void onResume(){super.onResume();if(list!=null){dark=getSharedPreferences("settings",0).getBoolean("dark",false);load();autoBackupIfNeeded();}}
 void requestSmsRoleThenPermissions(){if(Build.VERSION.SDK_INT>=29){RoleManager r=getSystemService(RoleManager.class);if(r!=null&&r.isRoleAvailable(RoleManager.ROLE_SMS)&&!r.isRoleHeld(RoleManager.ROLE_SMS)){startActivityForResult(r.createRequestRoleIntent(RoleManager.ROLE_SMS),9);return;}}permissions();}
 void permissions(){ArrayList<String> p=new ArrayList<>();if(Build.VERSION.SDK_INT>=23){p.add(Manifest.permission.READ_SMS);p.add(Manifest.permission.RECEIVE_SMS);p.add(Manifest.permission.SEND_SMS);p.add(Manifest.permission.READ_CONTACTS);if(Build.VERSION.SDK_INT>=33)p.add(Manifest.permission.POST_NOTIFICATIONS);requestPermissions(p.toArray(new String[0]),5);}}
 void ui(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(dark?darkBg:lightBg);
 TextView h=tv("My Messages",23,Color.WHITE);h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(22,0,0,0);h.setBackgroundColor(primary);root.addView(h,new LinearLayout.LayoutParams(-1,68));
 LinearLayout s=new LinearLayout(this);s.setPadding(8,4,8,4);search=new EditText(this);search.setHint("Search name, number or message");search.setSingleLine();search.setTextColor(fg());search.setHintTextColor(sub());s.addView(search,new LinearLayout.LayoutParams(0,58,1));Button add=bt("＋");s.addView(add,new LinearLayout.LayoutParams(62,58));root.addView(s);
 ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
 LinearLayout nav=new LinearLayout(this);nav.setPadding(2,2,2,2);for(String n:new String[]{"Inbox","Pinned","Archived","Blocked","More"}){Button x=bt(n);nav.addView(x,new LinearLayout.LayoutParams(0,60,1));x.setOnClickListener(v->{if(n.equals("More"))moreMenu();else show(n);});}root.addView(nav);
 setContentView(root);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){render(s.toString(),mode);}public void afterTextChanged(Editable e){}});add.setOnClickListener(v->newChat());}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==9)permissions();else if(r==10&&c==RESULT_OK&&pendingPrivate!=null){ThreadRow r0=pendingPrivate;pendingPrivate=null;openConversation(r0);}}
 void moreMenu(){new AlertDialog.Builder(this).setTitle("My Messages").setItems(new String[]{"Unread","Backup & Restore","Statistics","Cleanup","Settings"},(d,w)->{if(w==0)show("Unread");else if(w==1)startActivity(new Intent(this,BackupActivity.class));else if(w==2)startActivity(new Intent(this,StatsActivity.class));else if(w==3)startActivity(new Intent(this,CleanupActivity.class));else startActivity(new Intent(this,SettingsActivity.class));}).show();}
 void load(){data.clear();try{Cursor c=getContentResolver().query(Telephony.Sms.CONTENT_URI,new String[]{"thread_id","address","body","date","read","type"},null,null,"date DESC");HashSet<String> seen=new HashSet<>();if(c!=null){while(c.moveToNext()){String id=c.getString(0);if(id==null||seen.contains(id))continue;seen.add(id);ThreadRow r=new ThreadRow();r.thread=id;r.number=c.getString(1);r.body=c.getString(2);r.name=name(r.number);r.photo=photo(r.number);r.read=c.getInt(4);r.unread=unread(id);r.pin=pref("p",id);r.arc=pref("a",id);r.block=pref("b",id);r.privateChat=pref("v",id);data.add(r);}c.close();}}catch(Exception e){}render("",mode);}
 int unread(String id){int n=0;try{Cursor c=getContentResolver().query(Telephony.Sms.CONTENT_URI,new String[]{"_id"},"thread_id=? AND read=0",new String[]{id},null);if(c!=null){n=c.getCount();c.close();}}catch(Exception e){}return n;}
 String name(String n){try{Cursor c=getContentResolver().query(Uri.withAppendedPath(ContactsContract.PhoneLookup.CONTENT_FILTER_URI,Uri.encode(n)),new String[]{ContactsContract.PhoneLookup.DISPLAY_NAME},null,null,null);if(c!=null&&c.moveToFirst()){String x=c.getString(0);c.close();return x;}}catch(Exception e){}return n==null?"Unknown":n;}
 String photo(String n){try{Cursor c=getContentResolver().query(Uri.withAppendedPath(ContactsContract.PhoneLookup.CONTENT_FILTER_URI,Uri.encode(n)),new String[]{ContactsContract.PhoneLookup.PHOTO_THUMBNAIL_URI},null,null,null);if(c!=null&&c.moveToFirst()){String x=c.getString(0);c.close();return x;}}catch(Exception e){}return null;}
 void render(String q,String m){mode=m;list.removeAllViews();for(ThreadRow r:data){if(m.equals("Inbox")&&r.arc)continue;if(m.equals("Pinned")&&!r.pin)continue;if(m.equals("Archived")&&!r.arc)continue;if(m.equals("Blocked")&&!r.block)continue;if(m.equals("Unread")&&r.unread==0)continue;if(m.equals("Private")&&!r.privateChat)continue;String z=(r.name+" "+r.number+" "+r.body).toLowerCase();if(!z.contains(q.toLowerCase()))continue;row(r);}if(list.getChildCount()==0)list.addView(tv("No conversations",18,sub()));}
 void row(ThreadRow r){LinearLayout x=new LinearLayout(this);x.setGravity(Gravity.CENTER_VERTICAL);x.setPadding(8,5,8,5);x.setBackgroundColor(dark?darkBg:lightBg);
 ImageView av=new ImageView(this);if(r.photo!=null)try{av.setImageURI(Uri.parse(r.photo));}catch(Exception ignored){}else av.setImageResource(android.R.drawable.sym_def_app_icon);av.setBackgroundColor(purple);x.addView(av,new LinearLayout.LayoutParams(54,54));
 LinearLayout m=new LinearLayout(this);m.setOrientation(LinearLayout.VERTICAL);TextView nm=tv(r.name,17,fg());if(r.unread>0)nm.setTypeface(null,1);m.addView(nm);String preview=(r.body==null?"":r.body).replace("\n"," ");if(preview.length()>70)preview=preview.substring(0,70)+"…";m.addView(tv(preview,14,sub()));if(r.unread>0)m.addView(tv("● "+r.unread+" unread",12,purple));String lab=getPreferences(0).getString("l"+r.thread,"");if(!lab.isEmpty())m.addView(tv("🏷 "+lab,12,purple));if(r.privateChat)m.addView(tv("🔒 Private",12,purple));x.addView(m,new LinearLayout.LayoutParams(0,82,1));x.addView(tv(r.pin?"★":"",18,0xffd8961e));Button more=bt("⋮");more.setTextSize(18);more.setPadding(0,0,0,0);more.setOnClickListener(v->menu(r));x.addView(more,new LinearLayout.LayoutParams(46,60));
 x.setOnClickListener(v->{if(!selected.isEmpty()){toggleSelected(r,x);return;}open(r);});x.setOnLongClickListener(v->{toggleSelected(r,x);return true;});final float[] down={0};x.setOnTouchListener((v,e)->{if(e.getAction()==MotionEvent.ACTION_DOWN){down[0]=e.getX();return true;}if(e.getAction()==MotionEvent.ACTION_UP){float dx=e.getX()-down[0];if(dx<-180){deleteThread(r);return true;}if(dx>180){archiveThread(r);return true;}v.performClick();return true;}return true;});list.addView(x);}
 void deleteThread(ThreadRow r){try{getContentResolver().delete(Telephony.Sms.CONTENT_URI,"thread_id=?",new String[]{r.thread});}catch(Exception ignored){}load();}
 void archiveThread(ThreadRow r){save("a",r.thread,true);load();}
 void open(ThreadRow r){if(r.privateChat&&getSharedPreferences("settings",0).getBoolean("lock",false)){pendingPrivate=r;startActivityForResult(new Intent(this,LockActivity.class),10);return;}openConversation(r);}
 void openConversation(ThreadRow r){Intent i=new Intent(this,ConversationActivity.class);i.putExtra("thread",r.thread);i.putExtra("number",r.number);i.putExtra("name",r.name);startActivity(i);}
 void toggleSelected(ThreadRow r,View v){if(selected.contains(r.thread))selected.remove(r.thread);else selected.add(r.thread);v.setBackgroundColor(selected.contains(r.thread)?0xffffe1b8:(dark?darkBg:lightBg));if(!selected.isEmpty())bulkMenu();}
 void bulkMenu(){if(selected.isEmpty())return;new AlertDialog.Builder(this).setTitle(selected.size()+" conversations selected").setItems(new String[]{"Delete selected","Archive selected","Mark read","Mark unread","Clear selection"},(d,w)->{for(String id:new HashSet<>(selected))try{if(w==0)getContentResolver().delete(Telephony.Sms.CONTENT_URI,"thread_id=?",new String[]{id});else if(w==1)save("a",id,true);else{ContentValues cv=new ContentValues();cv.put("read",w==2?1:0);getContentResolver().update(Telephony.Sms.CONTENT_URI,cv,"thread_id=?",new String[]{id});}}catch(Exception ignored){}selected.clear();load();}).show();}
 void menu(ThreadRow r){String[] a={r.pin?"Unpin":"Pin",r.arc?"Unarchive":"Archive",r.block?"Unblock":"Block",r.unread>0?"Mark read":"Mark unread","Label","Call number","Open contact",r.privateChat?"Unmark private":"Make private","Report spam","Delete conversation"};new AlertDialog.Builder(this).setTitle(r.name).setItems(a,(d,w)->{try{
   if(w==0)save("p",r.thread,!r.pin);else if(w==1)save("a",r.thread,!r.arc);else if(w==2)save("b",r.thread,!r.block);else if(w==3){ContentValues v=new ContentValues();v.put("read",r.unread>0?1:0);getContentResolver().update(Telephony.Sms.CONTENT_URI,v,"thread_id=?",new String[]{r.thread});}
   else if(w==4){EditText e=new EditText(this);e.setHint("Work, Family, Bank");new AlertDialog.Builder(this).setTitle("Label").setView(e).setPositiveButton("Save",(dialog,z)->{saveLabel(r.thread,e.getText().toString());load();}).setNegativeButton("Cancel",null).show();return;}
   else if(w==5){startActivity(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+Uri.encode(r.number))));return;}
   else if(w==6){try{Intent ci=new Intent(Intent.ACTION_VIEW,Uri.withAppendedPath(ContactsContract.PhoneLookup.CONTENT_FILTER_URI,Uri.encode(r.number)));startActivity(ci);}catch(Exception ignored){}}
   else if(w==7){save("v",r.thread,!r.privateChat);return;}
   else if(w==8){save("b",r.thread,true);saveLabel(r.thread,"Spam");return;}
   else getContentResolver().delete(Telephony.Sms.CONTENT_URI,"thread_id=?",new String[]{r.thread});
 }catch(Exception ignored){}load();}).show();}
 void show(String m){render(search.getText().toString(),m);}
 void newChat(){EditText e=new EditText(this);e.setHint("Phone number");new AlertDialog.Builder(this).setTitle("New conversation").setView(e).setPositiveButton("Open",(d,w)->{Intent i=new Intent(this,ConversationActivity.class);i.putExtra("number",e.getText().toString());i.putExtra("name",e.getText().toString());startActivity(i);}).setNegativeButton("Cancel",null).show();}
 void saveLabel(String id,String v){getPreferences(0).edit().putString("l"+id,v==null?"":v.trim()).apply();}boolean pref(String p,String k){return getPreferences(0).getBoolean(p+k,false);}void save(String p,String k,boolean v){getPreferences(0).edit().putBoolean(p+k,v).apply();}
 void autoBackupIfNeeded(){if(!getSharedPreferences("settings",0).getBoolean("autoBackup",false))return;try{String day=new java.text.SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());String last=getSharedPreferences("settings",0).getString("lastAutoBackup","");if(!day.equals(last)){BackupUtil.autoBackup(this);getSharedPreferences("settings",0).edit().putString("lastAutoBackup",day).apply();}}catch(Exception ignored){}}
 static class ThreadRow{String thread,number,name,body,photo;int read,unread;boolean pin,arc,block,privateChat;}
}